### ISSUE TITLE
dataframe display

### ISSUE THREAD

**Issue by CinnyLin** [DSSGxUK/bmwi#34]
1. unemployment rate doesnt need to show four digits
2. rename column names for "last_month%" etc
3. be able to download dataframe as excel files

**Comment by CinnyLin** [comment]
**1. unemployment rate doesnt need to show four digits**

`pd.options.display.float_format = "{:,.2f}".format` is normally the solution but doesnt seem to render on streamlit

**Comment by prakharrathi25** [comment]
> **1. unemployment rate doesnt need to show four digits**
> 
> `pd.options.display.float_format = "{:,.2f}".format` is normally the solution but doesnt seem to render on streamlit

I got this working. Check it out here. 
![image](https://user-images.githubusercontent.com/38958532/130524385-54f3b559-9ead-48ef-99aa-2ace9e57e20f.png)

For now, it is only done during display. Do you want me to add this feature to the saved excel as well? I feel having precision isn't so bad in the excel but for display we can keep it like this. What do you think?

**Comment by prakharrathi25** [comment]
Will add this to other pages as well once the errors aren't there.
