### ISSUE TITLE
error analysis page add map viz back

### ISSUE THREAD

**Issue by CinnyLin** [DSSGxUK/bmwi#9]

**Comment by prakharrathi25** [comment]
BMWi really wants this so maybe we could add this back after the line plots? That might solve some things. @CinnyLin

**Comment by CinnyLin** [comment]
added map back
<img width="574" alt="Screen Shot 2021-08-20 at 4 10 35 PM" src="https://user-images.githubusercontent.com/45028889/130246335-fdce9338-55cf-44c5-8dd1-d5026eb6a1e6.png">

structural plots bug fixed
<img width="501" alt="Screen Shot 2021-08-20 at 4 10 51 PM" src="https://user-images.githubusercontent.com/45028889/130246371-ef55fcf3-7404-4349-9e34-52666775daa9.png">

linear regression model checkbox so doesnt load the whole page
<img width="501" alt="Screen Shot 2021-08-20 at 4 11 03 PM" src="https://user-images.githubusercontent.com/45028889/130246397-a30e666b-87d1-4582-bb80-c4a227471505.png">
